package com.pwb.liveroom.application.event;


public enum LiveroomEventType {

    PARTICIPANT_JOINED,
    PARTICIPANT_LEFT,
    PARTICIPANT_KICKED,


    MEDIA_STATE_CHANGED,
    PARTICIPANT_MIC_MUTED_BY_OWNER,

    PARTICIPANT_MIC_UNMUTED,


    OWNER_LEFT,
    OWNER_REJOINED,

    ROOM_CAPACITY_CHANGED,

    CAPACITY_REACHED,

    JOIN_REQUEST_CREATED,
    JOIN_REQUEST_CANCELLED,

    REQUEST_APPROVED,
    REQUEST_REJECTED_BY_OWNER,
    REQUEST_REJECTED_BY_CAPACITY,
    REQUEST_LOCKED,


    CHAT_MESSAGE_RECEIVED,


    MUSIC_PLAYBACK_STATE_CHANGED,

    MUSIC_SONG_CHANGED,

    RTC_OFFER,
    RTC_ANSWER,
    RTC_ICE_CANDIDATE,

    ROOM_MANUAL_ENDED,

    ROOM_AUTO_ENDED,
    ROOM_REVIVED,
    ROOM_REOPENED
}