export const LiveroomErrorCode = {
  ROOM_NOT_FOUND: "LR_001",
  ROOM_ENDED: "LR_002",
  ROOM_NAME_DUPLICATE: "LR_003",
  ROOM_NAME_INVALID: "LR_004",
  ROOM_CODE_GENERATION_FAILED: "LR_005",
  ROOM_CODE_LOOKUP_THROTTLED: "LR_006",
  CANNOT_REOPEN: "LR_007",
  UNDO_WINDOW_EXPIRED: "LR_008",
  GRACE_INVALID: "LR_009",
  ROOM_FORCE_ENDED_ROLE_CHANGE: "LR_010",

  NOT_OWNER: "LR_020",
  SELF_JOIN_NOT_ALLOWED: "LR_022",

  REQUEST_NOT_FOUND: "LR_030",
  REQUEST_EXPIRED: "LR_031",
  REQUEST_LOCKED: "LR_032",
  DUPLICATE_REQUEST: "LR_033",
  ALREADY_APPROVED: "LR_034",

  ROOM_FULL: "LR_040",
  ALREADY_IN_ROOM: "LR_041",
  NOT_IN_SESSION: "LR_042",
  PARTICIPANT_NOT_FOUND: "LR_043",
  APPROVAL_REQUIRED: "LR_044",

  SELF_KICK_NOT_ALLOWED: "LR_050",
  KICKED_COOLDOWN: "LR_051",
  MIC_MUTE_COOLDOWN: "LR_052",

  CHAT_EMPTY: "LR_060",
  CHAT_TOO_LONG: "LR_061",

  MUSIC_NOT_OWN_SONG: "LR_070",
  MUSIC_NOT_READY: "LR_071",
  MUSIC_NOT_PLAYING: "LR_072",
  MUSIC_INVALID_POSITION: "LR_073",
  MUSIC_INVALID_VOLUME: "LR_074",
  MUSIC_STATE_CONFLICT: "LR_075",
  MUSIC_OWNER_ABSENT: "LR_076",
  MUSIC_SONG_LOAD_FAILED: "LR_077",

  WS_UNAUTHORIZED: "LR_080",

  RTC_SELF_SIGNALING: "LR_090",
  RTC_PAYLOAD_TOO_LARGE: "LR_091",
  RTC_PAYLOAD_INVALID: "LR_092",
} as const;

export type LiveroomErrorCodeValue =
  (typeof LiveroomErrorCode)[keyof typeof LiveroomErrorCode];

export const ALREADY_SEATED_CODES: ReadonlySet<string> = new Set<string>([
  LiveroomErrorCode.ALREADY_IN_ROOM,
]);

export const NEEDS_JOIN_REQUEST_CODES: ReadonlySet<string> = new Set<string>([
  LiveroomErrorCode.APPROVAL_REQUIRED,
  LiveroomErrorCode.NOT_IN_SESSION,
]);

export const ROOM_GONE_CODES: ReadonlySet<string> = new Set<string>([
  LiveroomErrorCode.ROOM_NOT_FOUND,
  LiveroomErrorCode.ROOM_ENDED,
]);