spring:
  flyway:
    enabled: true
    locations:
      - classpath:db/migration/iam
      - classpath:db/migration/liveroom
      - classpath:db/migration/audio
  mongodb:
    auto-index-creation: true
  data:
    redis:
      repositories:
        enabled: true
