spring:
  application:
    name: backend
  profiles:
    active: local
  config:
    import:
      - optional:classpath:config/application-shared.yaml
      - optional:classpath:config/application-iam.yaml
      - optional:classpath:config/application-liveroom.yaml
      - optional:classpath:config/application-audio.yaml
