export const IamErrorCode = {
  EMAIL_ALREADY_REGISTERED: "IAM_001",
  WEAK_PASSWORD: "IAM_002",
  USER_NOT_FOUND: "IAM_003",
  LOGIN_BAD_CREDENTIALS: "IAM_004",
  ACCOUNT_LOCKED: "IAM_005",
  ACCOUNT_INACTIVE: "IAM_006",
  ACCOUNT_NOT_VERIFIED: "IAM_007",
  REFRESH_TOKEN_INVALID: "IAM_011",
  REFRESH_TOKEN_EXPIRED: "IAM_012",
  REFRESH_TOKEN_REUSED: "IAM_013",
  RATE_LIMITED: "IAM_014",
  AUTH_INVALID_CURRENT_PASSWORD: "IAM_015",
  AUTH_PASSWORD_REUSED: "IAM_016",
  AUTH_OTP_INVALID: "IAM_021",
  AUTH_OTP_EXPIRED: "IAM_022",
  AUTH_RATE_LIMIT_EXCEEDED: "IAM_026",
  AUTH_OTP_DAILY_LIMIT_EXCEEDED: "IAM_027",
  AUTH_PASSWORD_RECENTLY_USED: "IAM_030",
  AUTH_RESET_TOKEN_INVALID: "IAM_031",
  AUTH_OAUTH_USER_NO_PASSWORD: "IAM_033",
  SERVICE_UNAVAILABLE: "IAM_034",
  PROFILE_INVALID_AVATAR_FORMAT: "IAM_PROFILE_001",
  PROFILE_AVATAR_TOO_LARGE: "IAM_PROFILE_002",
} as const;

export type IamErrorCodeValue = (typeof IamErrorCode)[keyof typeof IamErrorCode];

export const EMAIL_ALREADY_TAKEN_CODES: ReadonlySet<string> = new Set<string>([
  IamErrorCode.EMAIL_ALREADY_REGISTERED,
  "CONFLICT",
]);

export const RATE_LIMIT_CODES: ReadonlySet<string> = new Set<string>([
  IamErrorCode.RATE_LIMITED,
  IamErrorCode.AUTH_RATE_LIMIT_EXCEEDED,
]);
